### ISSUE TITLE
Исправить ошибки

### ISSUE THREAD

**Issue by Dennyre** [Dennyre/area_test#1]
1) Создать новую ветку
2) Исправить ошибки в проекте
3) Закоммитить и изменить ветку
4) Создать Pull Request

**Comment by Mrscorpion45** [comment]
Всем хаааааааааай

**Comment by Mrscorpion45** [comment]
Список дел на сегодня

1. [x] поспать
2. [x] поесть
3. [x] комп
4. [x] поесть
5. [x] поспать
6. [x] комп
7. [x] комп
8. [x] поспать
9. [x] поесть
10. [x] подрочить
11. [x] поесть

**Comment by Mrscorpion45** [comment]
пон
